### ISSUE TITLE
Side loading zim via sd card ios

### ISSUE THREAD

**Issue by ramko93** [kiwix/apple#186]
Currently ipad os on my 6th generation ipad detects zim files from external sd but not able to load it anyway,share sheet doesn't even show kiwix as an option. Using version kiwix 1.10

**Comment by kelson42** [comment]
What happen exactly if you try to open it from the Kiwix library?

**Comment by ramko93** [comment]
external source becomes invisible 
Back to files app becomes visible #[](url)
![CD8302A3-E00A-4550-B624-E928B57DE6C8](https://user-images.githubusercontent.com/56144733/66191642-76003800-e6ac-11e9-9554-0dc15d360e4f.png)
![03008C38-9456-4EA2-8ADB-33A224847497](https://user-images.githubusercontent.com/56144733/66191643-7698ce80-e6ac-11e9-9e19-f1d19eb259cd.png)
![20A59ECB-358F-4AE0-9141-61DC33187A82](https://user-images.githubusercontent.com/56144733/66191644-7698ce80-e6ac-11e9-82f3-24e7ca743be8.png)
![83210D46-10A1-44BA-9518-F36CA4B33172](https://user-images.githubusercontent.com/56144733/66191645-7698ce80-e6ac-11e9-99cb-c02e4cea6e5c.png)
![F1522A08-E6F1-407B-883D-93A085A230FD](https://user-images.githubusercontent.com/56144733/66191646-77316500-e6ac-11e9-81f2-869fc41f24ba.png)
![E8AC98AB-01E8-4600-9701-554AC5680DE6](https://user-images.githubusercontent.com/56144733/66191647-77316500-e6ac-11e9-969b-c41f18c356be.png)
![2BBDEC72-EECB-4C5E-9AC3-C1EE95019FF4](https://user-images.githubusercontent.com/56144733/66191649-77316500-e6ac-11e9-9c00-00887f358590.png)
![DEEB41D4-F825-475F-A2C7-35BD20C4AAEF](https://user-images.githubusercontent.com/56144733/66191650-77316500-e6ac-11e9-8b86-3efbef4d00d1.png)

**Comment by kelson42** [comment]
@automactic Any idea?

**Comment by ramko93** [comment]
I even tried a 1 gb zim file;results same

**Comment by ramko93** [comment]
![17063493-D664-4C13-8A0F-B680A0EEF259](https://user-images.githubusercontent.com/56144733/66192350-e3609880-e6ad-11e9-9893-91e397da2344.png)

**Comment by automactic** [comment]
No clue why. @ramko93 could you try the latest version of the app (1.11) with latest version of iOS (13.4 or 13.4.1)? It could because the app was not build for IOS 13 at that time. 

Also I have no way to test opening zim file from iOS device. I don't have one of those USB-C iPad pros and I don't have a dongle.

**Comment by automactic** [comment]
@kelson42 @Popolechien Do you guys have a way to test it out?

**Comment by ramko93** [comment]
Thanks guys issue resolved after updating to ios 13.4

**Comment by ramko93** [comment]
Resolved

**Comment by pallazola** [comment]
I'm still having this issue with loading from external USB. Any one else? Thoughts?
