### ISSUE TITLE
Kiwix-macOS doesn't show previously-loaded ZIM files

### ISSUE THREAD

**Issue by srousset** [kiwix/apple#294]
I recently installed Kiwix 2.1.1 (2.1.4) on macOS 10.15.5. I loaded a Wikipedia (and only one), all went well.

Closed Kiwix. Re-opened it. Nothing in the list. Opened that same Wikipedia, it now shows twice in the list.

Closed Kiwix. Re-opened it. Nothing in the list. Opened that same Wikipedia, it now shows twice in the list. Repeat as long as you wish.

Certainly not a show-stopper, but clearly an unintended feature.

Best regards, Stéphane

P.S.: I'm attaching screenshots when  1) I just re-opened Kiwix,  2) I loaded the Wikipedia again,  and 3) after I closed and re-opened Kiwix. (Yes, 3 is the same as 1.) I guess the text was pretty self-explanatory anyway.

<img width="1143" alt="Capture d’écran 2020-07-15 à 22 37 29" src="https://user-images.githubusercontent.com/20866309/87594267-01533300-c6ed-11ea-908d-eaf3d591b253.png">
<img width="1143" alt="Capture d’écran 2020-07-15 à 22 37 46" src="https://user-images.githubusercontent.com/20866309/87594326-129c3f80-c6ed-11ea-984b-57bf3cbe8c18.png">
<img width="1143" alt="Capture d’écran 2020-07-15 à 22 37 59" src="https://user-images.githubusercontent.com/20866309/87594356-1cbe3e00-c6ed-11ea-8066-134c17fdb3b7.png">

**Comment by rgaudin** [comment]
I am facing the same behavior as well

**Comment by harryhirsch0** [comment]
Same problem here, very annoying.

**Comment by kelson42** [comment]
@automactic This  looks like a regression, isn't it?

**Comment by akuma-sama** [comment]
I have same problem on Kiwix version 2.1.1 (2.1.4) on MacOs Catalina 10.15.6.
1st screenshot i opened Kiwix
2nd added .zim and close Kiwix
3nd ive opeded Kiwix
4th ive added again .zim, but there are twice. 
![Screenshot 2020-08-04 at 19 40 45](https://user-images.githubusercontent.com/54769591/89326603-d83e1680-d68a-11ea-8f97-c9df89e038b0.png)
![Screenshot 2020-08-04 at 19 41 07](https://user-images.githubusercontent.com/54769591/89326628-e429d880-d68a-11ea-9393-b8747837c8c2.png)
![Screenshot 2020-08-04 at 19 41 17](https://user-images.githubusercontent.com/54769591/89326631-e5f39c00-d68a-11ea-9d58-d7e6159fa0f1.png)
![Screenshot 2020-08-04 at 19 41 28](https://user-images.githubusercontent.com/54769591/89326635-e68c3280-d68a-11ea-8a6e-8142db4117d1.png)

**Comment by automactic** [comment]
Fixed in #304. The fix is going to part of the upcoming 2.1.2 release

**Comment by harryhirsch0** [comment]
This bug is still present in version 2.1.2 in some way... After a reboot the list of Zim Files is empty and I have to add it again.

**Comment by kelson42** [comment]
@harryhirsch0 Thank you for coming back on this ticket - even with a bad news. Just to be sure I get properly the proble, here is what you do?
1 - Install version 2.1.2
2 - Add a few ZIM files
3 - Exit Kiwix
4 - Launch Kiwix - the ZIM files are there
5 - Exit Kiwix and restart the computer
6 - Launch Kiwix - the library is empty

Thank you in advance for confirmation.

**Comment by harryhirsch0** [comment]
> 1 - Install version 2.1.2
> 2 - Add a few ZIM files
> 3 - Exit Kiwix
> 4 - Launch Kiwix - the ZIM files are there
> 5 - Exit Kiwix and restart the computer
> 6 - Launch Kiwix - the library is empty

Hi,
yes, that's exactly what happens (macOS 10.15.6). I repeated several times, same result.
But between reboots, the list of Zim files is persistent - that's good news...

**Comment by kelson42** [comment]
> But between reboots, the list of Zim files is persistent - that's good news...

OK, then there is not bug.

**Comment by rgaudin** [comment]
@kelson42 I disagree. Why would the ZIM list not being persisted after a reboot not be a bug? The list is persisted on all the other readers (ios, android, desktop) so this is the expected behavior.

Tested and confirmed: persists during the session (even after log-out and in) but a reboot clears it completely.

**Comment by kelson42** [comment]
@rgaudin @harryhirsch0 has written "between reboots, the list of Zim files is persistent - that's good news...". So no empty list.

**Comment by rgaudin** [comment]
kelson42 are you saying it is Ok that the list is cleared when the computer is rebooted ?

**Comment by kelson42** [comment]
@rgaudin no

**Comment by rgaudin** [comment]
Ok then I think you misunderstood his earlier comment. we're on the same page

**Comment by kelson42** [comment]
This is probably fixed in next release `3.0.0`

**Comment by kelson42** [comment]
This has been fixed and works properly now.
