### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by gsobala** [kiwix/apple#475]
Version 3.0 released today shows a completely black screen on latest version of iOS and iphone 13 Pro Max. The Kiwix screen looks normal in the app scroller but again goes black when picked / maximised. Switching the phone day / night settings does not help.

**Comment by Alimjoo** [comment]
This happens ios 14.0.1 also. And it crashes

**Comment by practik** [comment]
Also happening on an iPhone 7 running iOS 15.7.

**Comment by automactic** [comment]
Does the app eventually get killed by the system if you just let it sit there in the foreground?

**Comment by jonathanyhsu** [comment]
So far I've left kiwix in the foreground for 30 minutes and although the iPhone locks the screen periodically per my settings, the app has not been killed by the system.

**Comment by automactic** [comment]
OK that might be good news, at least app launch did not get stuck somewhere. I don't exactly know what issue you could be having for sure, since I (also on iOS 16.1.1) cannot reproduce and other testers did not report this issue.

@jonathanyhsu Could you sign up for TestFlight via [this link](https://testflight.apple.com/join/pKozwnSU)? Look for build 108 after App Store reviews it, which should take around 24hrs

**Comment by jonathanyhsu** [comment]
@automactic With the 3.0.1 (build 108) version, I am able to use kiwix now and browse my 95.2GB wikipedia download (dated May 1, 2022).

**Comment by automactic** [comment]
@jonathanyhsu Hey, could you try build 109? In 108 I disabled iPad multi window support, which apparently is causing issues on some device. In 109, I reenabled it with a slightly different config, not sure if that works. 

There seems to be very little documentation on how I am actually supposed to set this up, but I want to just confirm with you before I push an update

**Comment by neutor** [comment]
Same, black screen on opening the app. iOS 16.1.1 iPhone 13 Pro. Tried reboot.

**Comment by jonathanyhsu** [comment]
@automactic Build 109 also works for me, I am able to start the app, browse my library, and read articles on my one Wikipedia image (95.2GB, May 1 2022)

**Comment by automactic** [comment]
@jonathanyhsu Great, thanks for your help with testing. I will make a update with 109 now

**Comment by jonathanyhsu** [comment]
@automactic In some unfortunate news, I just tested build 109 on my iPad Pro and I am also getting the black unresponsive screen. The app store version previously published (3.0) also has the black screen issue similar to what was on my iPhone 14 Pro.

Platform: 2018 11" iPad Pro
OS: iPadOS 16.1.1 (20B101)
App version: Kiwix 3.0.1 (build 109)

Please feel free to let me know if you want any further debugging steps taken, but I tried killing the app and restarting it just like on the phone, and it did not resolve the issue.

**Comment by gsobala** [comment]
Not fixed in 3.0.1

**Comment by practik** [comment]
3.0.1 doesn't fix it for me either, but it does seem slightly different from 3.0 in one way. If I exit the app and then return to it, either from the app switcher or by tapping the app icon, before the screen goes black I see a very brief flash of the last page I had open. FWIW, I don't remember that happening in 3.0.

(iPhone 7, iOS 15.7)

**Comment by automactic** [comment]
@jonathanyhsu Does build 108 work on your iPad?

**Comment by gsobala** [comment]
I fixed it with 3.0.1 by deleting the app (and losing all my library) and then re-installing.

**Comment by jonathanyhsu** [comment]
@automactic Thanks for suggesting that; yes, build 108 does work on my 2018 11" iPad Pro.

**Comment by u35253** [comment]
"Black screen only" occurs for me in Kiwix 3.0 on iOS 15.0.1 on iPhone Xs.  After updating to Kiwix 3.0.1, the "black screen only" problem still occurs 100% of time.

I tried rebooting both before and after upgrading Kiwix to 3.0.1.

Please let me know if I can do anything useful to help debug and get this resolved.

**Comment by HerrTimbo** [comment]
Only opens to black Screen.
iPhone 14 Pro
iOS 16.1.1
Kiwix 3.0.1

**Comment by automactic** [comment]
@jonathanyhsu Thanks for your help. I will make another release with 108 and see if that helps

**Comment by davythefatboy** [comment]
Deleting app and reinstalling solved the black screen issue. Yes, had to redownload ZIM files.  Subsequently updated to 3.02, also works fine. Thanks for the good work, much appreciated.

**Comment by u35253** [comment]
Replicating a portion of @davythefatboy report, updating to Kiwix 3.0.2 on iOS 15.7.1 fixed it on iPhone Xs (no more black screen only).  Doing just this update, I did not have to remove/re-add zim files.  Thank you very much for the very useful app and for the fast fix.

**Comment by jonathanyhsu** [comment]
@automactic Build 3.0.2 from the App Store works for both my iPhone 14 Pro (iOS 16.1.1) and 2018 11" iPad Pro (iPadOS 16.1.1). Thanks!

**Comment by RuochenFu21** [comment]
Happened again to me on 3.2

**Comment by kelson42** [comment]
@RuochenFu21 We are just about releasing 3.3.0. Please let us know when you still have this problem with this new version.
